app = "grinzine"
primary_region = "iad"

[build]
  # If you use a Dockerfile, comment out the builder line below
  # builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "1s"
    restart_limit = 6
